# Seed needs to be set at top of yaml, before objects with parameters are made
seed: 1234
__set_seed: !apply:torch.manual_seed [!ref <seed>]
# Training params
N_epochs: 10
dataloader_options:
    batch_size: 4

lr: 0.01
opt_class: !name:torch.optim.Adam
    lr: !ref <lr>